### ISSUE TITLE
Dialog Window appears clipped when setting alpa parameter to true

### ISSUE THREAD

**Issue by Yasserkhayyal** [yukuku/ambilwarna#15]
I have a problem with the dialog window size in the portrait mode when running my app against S5 phone. here is a snapshot:
![screenshot_2016-01-24-13-42-40 1](https://cloud.githubusercontent.com/assets/12128622/12536026/897cb31a-c2a0-11e5-8bcf-6e6591731a36.png)
How to solve this issue?

**Comment by shobhitic** [comment]
I know this is a closed issue but I would really like to know the solution to this. Facing the same problem.

**Comment by Yasserkhayyal** [comment]
Add this snippet after dialog.show() :

```
View view = dialog.getDialog().findViewById(yuku.ambilwarna.R.id.ambilwarna_viewSatBri);
        ViewGroup.LayoutParams params = view.getLayoutParams();

        //reduces the size of the color picker view to show the hue picker bar
        params.width -= (int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 48,
                getResources().getDisplayMetrics());
        ;
view.setLayoutParams(params);
```

**Comment by shobhitic** [comment]
Thanks!

**Comment by Yasserkhayyal** [comment]
Glad it could help. Happy Coding :)
