### ISSUE TITLE
[Question] Proper Crediting?

### ISSUE THREAD

**Issue by Sciguy429** [yukuku/ambilwarna#19]
This is my first time using a library in a app I made and I am planning on putting it on google play.

My question is how do I credit you for your work? Im sorry if this is a dumb question but this is literally my first time using a library and I don't want to make a anyone mad at me, so far I've coded everything else.

Thanks,
-Sciguy

**Comment by denisk20** [comment]
Hi Sciguy,
Our library is released under Apache2 license, so no credit is needed even for commercial use (although a reference to the library would be appreciated :)

**Comment by Sciguy429** [comment]
Thanks for the clarification :)
