### ISSUE TITLE
When in landscape mode the slider that selects the colour disappears on Nexus One

### ISSUE THREAD

**Issue by digitalrep** [yukuku/ambilwarna#4]

**Comment by denisk20** [comment]
Does this happen when you rotate the screen after opening the dialog? Or the slider just doesn't appear?

**Comment by digitalrep** [comment]
It's the emulator that comes with Android Studio. I start the application in landscape mode. The slider is situated outside the bounds of the dialog box. I mean the activity is screenOrientation:sensorLandscape. So no there's no rotation.

**Comment by denisk20** [comment]
OK, I can see it:
![image](https://cloud.githubusercontent.com/assets/3080318/8961548/8f2d16b0-361e-11e5-9ac1-b525f11e70d0.png)

Thanks for reporting it, will try to fix it.

**Comment by artisan-android** [comment]
Hi，I solve this issue by with method ：
AmbilWarnaDialog dialog = new AmbilWarnaDialog(mContext, currentValue, this);
dialog.show();
View view = dialog.getDialog().findViewById(yuku.ambilwarna.R.id.ambilwarna_viewSatBri);
ViewGroup.LayoutParams params = view.getLayoutParams();
params.width -= AsTypeCastUtils.dip2px(mContext,48);
view.setLayoutParams(params);
