### ISSUE TITLE
No resource identifier found for attribute 'layerType' in package 'android'

### ISSUE THREAD

**Issue by sallu1001** [yukuku/ambilwarna#5]
Hi 

Thanks for sharing your efforts, I just need to check that I am getting this error
"No resource identifier found for attribute 'layerType' in package 'android'", after impoting the project in Eclipse. Kindly let me know what's the problem.

Thanks

**Comment by denisk20** [comment]
I don't think we support Eclipse since it is officially deprecated: 
http://android-developers.blogspot.com/2015/06/an-update-on-eclipse-android-developer.html
Please try to import into Android Studio and let us know if you have any issues.

**Comment by sallu1001** [comment]
Ok thanks for the reply.
