### ISSUE TITLE
White square instead of color chooser on M

### ISSUE THREAD

**Issue by denisk20** [yukuku/ambilwarna#7]
The color chooser needs to be fixed on Android M.
![screenshot](https://cloud.githubusercontent.com/assets/3080318/9469576/843a79ea-4b50-11e5-8b87-41fedbf7be4f.png)

**Comment by stefan2606** [comment]
buildToolsVersion "23.0.1"

**Comment by denisk20** [comment]
@stefan2606 Thank you very much!

**Comment by yukuku** [comment]
@stefan2606 Interesting that this is fixed by just the build tools version change. I could not find any release notes about this version though. Do you happen to find any?

**Comment by stefan2606** [comment]
Nope.
It was just luck that I figured this out.
