### ISSUE TITLE
preference color picker programmatically

### ISSUE THREAD

**Issue by xbandx68** [yukuku/ambilwarna#8]
and I write this code

PreferenceCategory category = new PreferenceCategory(getActivity().getBaseContext());
            category.setTitle("Categorie");
            screen.addPreference(category);

AmbilWarnaPreference list1 = new AmbilWarnaPreference(getActivity().getBaseContext(), null);
        list1.setTitle("Sorbetti");
        list1.setSummary("Sorbetti gelao");
        list1.setDefaultValue(0xff6699cc);
        list1.setKey("Sorbetti_key");
        category.addPreference(list1);
        setPreferenceScreen(screen);

**Comment by denisk20** [comment]
Can you post the stacktrace of the crash? We might be just missing a one-arg constructor in `AmbilWarnaPreference`.

**Comment by xbandx68** [comment]
sorry no crash, only a dubt for this code:
AmbilWarnaPreference list1 = new AmbilWarnaPreference(getActivity().getBaseContext(), null);

is correct the null parameter? or not all works fine with null.

thanks

**Comment by denisk20** [comment]
I guess it's correct, in fact in many SDK View constructors have `AttributeSet` parameter marked as Nullable in order to let us know that `null` is a valid parameter:

```
public TextView(Context context, @Nullable AttributeSet attrs) {
    this(context, attrs, com.android.internal.R.attr.textViewStyle);
}
```
