### ISSUE TITLE
Not working with Android M

### ISSUE THREAD

**Issue by lukeisontheroad** [yukuku/ambilwarna#9]
Unfortunately it doesn't seem to work with the compileSDKVersion 23. Proguard shows me the following warning:

Warning:yuku.ambilwarna.widget.AmbilWarnaPrefWidgetView: can't find referenced method 'float floor(float)' in library class android.util.FloatMath

I am able to ignore it with -dontwarn yuku.ambilwarna.widget.AmbilWarnaPrefWidgetView but then the Picker is not working at all:

<img width="388" alt="screen shot 2015-09-25 at 09 45 29" src="https://cloud.githubusercontent.com/assets/4269449/10095433/3498c554-636a-11e5-9754-add9b21f4284.png">

**Comment by yukuku** [comment]
This seems to have been fixed on the latest release, but it has not been pushed to the Maven repository.

@denisk20 Could you help publish the latest version to the Maven repository? Thanks!

**Comment by denisk20** [comment]
@yukuku Absolutely, I was hoping to fix the landscape orientation bug and push in a batch. I can push the landscape fix later though as it seems to be more important to unblock people working with M. I'll push today or tomorrow.

**Comment by lukeisontheroad** [comment]
Thanks a lot, keep up the awesome work!

**Comment by denisk20** [comment]
@lukeisontheroad I have pushed version `2.0.1` to maven central; can you please try it out?
https://repo1.maven.org/maven2/com/github/yukuku/ambilwarna/2.0.1/

**Comment by lukeisontheroad** [comment]
@denisk20 It works as expected. Thanks for your efforts!
